export const ADD_COLUMN = 'ADD_COLUMN'
export const REMOVE_COLUMN = 'REMOVE_COLUMN'
export const SET_COLUMNS = 'SET_COLUMNS'

export const EDIT_COLUMN = 'EDIT_COLUMN'
export const EDIT_COLUMN_SUCCESS = 'EDIT_COLUMN_SUCCESS'
export const EDIT_COLUMN_FAIL = 'EDIT_COLUMN_FAIL'
